name: hydromt

channels:
  - conda-forge

dependencies:
  - affine
  - click
  - black
  - bottleneck
  - cartopy # to run examples
  - dask>=2.30
  - descartes # to run examples
  - entrypoints
  - flit>=3.2
  - gdal>=3.1
  - geopandas
  - jupyter # to run examples
  - netcdf4
  - matplotlib # to run examples
  - numba
  - numpy
  - openpyxl
  - pandas
  - pip
  - pyflwdir>=0.4.7
  - pygeos>=0.8
  - python>=3.8
  - rasterio
  - requests
  - scipy
  - xarray
  - zarr
  pip:
    - git+https://github.com/Deltares/hydromt.git