---
name: Build and publish HydroMT to DockerHub

on:
  release:
    types:
      - published
  push:
    tags:
      - v*

jobs:
  publish-docker-image:
    if: ${{ github.event_name == 'release' || github.event.act }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and test
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          target: full

      - name: Run Tests
        run: docker run --rm -it hydromt pytest

      #build should be cached from previous steps
      - name: Build and push full image
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          target: full
          push: ${{ !github.event.act }}
          tags: deltares/hydromt
      - name: Build and push min image
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          target: min
          push: ${{ !github.event.act }}
          tags: deltares/hydromt:min
      - name: Build and push slim image
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          target: slim
          push: ${{ !github.event.act }}
          tags: deltares/hydromt
      