---
name: Build and publish HydroMT to DockerHub

on:
  release:
    types:
      - published

  workflow_dispatch:
    inputs:
      publish:
        description: 'Actually push images'
        required: true
        type: boolean
        default: false


jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.TEST_DOCKERHUB_USERNAME }}
          password: ${{ secrets.TEST_DOCKERHUB_TOKEN }}

      - name: generate envs
        run: |
          pip install tomli
          python make_env.py -p '3.11' -o full-environment.yml full

      - name: Build and test
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: deltares/hydromt:full
          load: true
          target: full

      - name: Run Tests
        run: docker run --rm hydromt pytest

      #build should be cached from previous steps
      - name: Build and push full image
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          target: full
          push:  ${{ inputs.publish }}
          tags: deltares/hydromt:full

      - name: Build and push min image
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          target: min
          push:  ${{ inputs.publish }}
          tags: deltares/hydromt:min

      - name: Build and push slim image
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          target: slim
          push:  ${{ inputs.publish }}
          tags: deltares/hydromt:slim
