---
name: Build and publish HydroMT to DockerHub

on:
  release:
    types:
      - published

  workflow_dispatch:
    inputs:
      publish:
        description: 'Actually push images'
        required: true
        type: boolean
        default: false
      version:
        description: 'The version to publish'
        required: true
        type: text


jobs:
  publish-docker-image:
    strategy:
      fail-fast: false
      matrix:
        flavour: ['min','slim','full']
    name: ${{ matrix.flavour }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Setup variables
        run: |
          if [ "${{ github.event_name }}" == "release" ]; then
            echo "should_publish=true" >> $GITHUB_ENV
            echo "version=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          elif [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_ENV
            echo "should_publish=${{ github.event.inputs.publish }}" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.TEST_DOCKERHUB_USERNAME }}
          password: ${{ secrets.TEST_DOCKERHUB_TOKEN }}

      - name: generate envs
        run: |
          pip install tomli
          python make_env.py -p '3.11' -o ${{ matrix.flavour }}-environment.yml ${{ matrix.flavour }}

      - name: Build and push ${{ matrix.flavour }} image
        uses: docker/build-push-action@v4
        with:
          context: .
          target: ${{ matrix.flavour }} #
          push:  ${{ env.should_publish }}
          tags: deltares/hydromt:${{ env.version }}-${{ matrix.flavour }}

      - name: Build and push latest image
        if: matrix.flavour == 'slim'
        uses: docker/build-push-action@v4
        with:
          context: .
          target: ${{ matrix.flavour }} #
          push:  ${{ env.should_publish }}
          tags: deltares/hydromt:${{ env.version }}, deltares/hydromt:latest
